### ISSUE TITLE
Nullpointer Exception: onBindView

### ISSUE THREAD

**Issue by joecks** [joecks/clipboard-actions-community#9]
App-Version
    201
Android-Version
    Android 4.11
Gerät
    HTC EVO 4G LTE (jewel)

java.lang.NullPointerException
	at android.widget.Switch.onPopulateAccessibilityEvent(Switch.java:534)
	at android.view.View.dispatchPopulateAccessibilityEventInternal(View.java:4638)
	at android.view.View.dispatchPopulateAccessibilityEvent(View.java:4628)
	at android.preference.TwoStatePreference.sendAccessibilityEvent(TwoStatePreference.java:197)
	at android.preference.SwitchPreference.onBindView(SwitchPreference.java:108)
	at de.halfreal.clipboardactions.preferences.SwitchPreference.onBindView(SwitchPreference.java:51)
	at android.preference.Preference.getView(Preference.java:453)
	at android.preference.PreferenceGroupAdapter.getView(PreferenceGroupAdapter.java:221)
	at android.widget.AbsListView.obtainView(AbsListView.java:2350)
	at android.widget.ListView.makeAndAddView(ListView.java:1937)
	at android.widget.ListView.fillSpecific(ListView.java:1483)
	at android.widget.ListView.layoutChildren(ListView.java:1765)
	at android.widget.AbsListView.onLayout(AbsListView.java:2178)
	at android.view.View.layout(View.java:13836)
	at android.view.ViewGroup.layout(ViewGroup.java:4380)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
	at android.view.View.layout(View.java:13836)
	at android.view.ViewGroup.layout(ViewGroup.java:4380)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:13836)
	at android.view.ViewGroup.layout(ViewGroup.java:4380)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
	at android.view.View.layout(View.java:13836)
	at android.view.ViewGroup.layout(ViewGroup.java:4380)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:13836)
	at android.view.ViewGroup.layout(ViewGroup.java:4380)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
	at android.view.View.layout(View.java:13836)
	at android.view.ViewGroup.layout(ViewGroup.java:4380)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:13836)
	at android.view.ViewGroup.layout(ViewGroup.java:4380)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1649)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1507)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1420)
	at android.view.View.layout(View.java:13836)
	at android.view.ViewGroup.layout(ViewGroup.java:4380)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
	at android.view.View.layout(View.java:13836)
	at android.view.ViewGroup.layout(ViewGroup.java:4380)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2112)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1913)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1154)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4667)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:734)
	at android.view.Choreographer.doCallbacks(Choreographer.java:560)
	at android.view.Choreographer.doFrame(Choreographer.java:529)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:719)
	at android.os.Handler.handleCallback(Handler.java:615)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:155)
	at android.app.ActivityThread.main(ActivityThread.java:5454)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by joecks** [comment]
Seems to be resolved.
